// tokens/tokens.json + src/*.css -> dist/*. No dependencies.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(root, "tokens/tokens.json"), "utf8"));
const read = (p) => readFileSync(join(root, p), "utf8");
const out = (p, s) => writeFileSync(join(root, "dist", p), s);
const banner = "/* GENERATED by scripts/build.mjs. Edit tokens/tokens.json or src/*.css. */\n";

const varName = (group, name) =>
  ({ color: "", font: "", size: "text-", radius: "radius-", space: "space-", shadow: "shadow-", layout: "layout-" })[group] + name;

const lines = [];
for (const [group, items] of Object.entries(tokens)) {
  if (group.startsWith("$")) continue;
  for (const [name, t] of Object.entries(items)) lines.push(`  --${varName(group, name)}: ${t.value};`);
}
const tokensCss = `${banner}:root {\n${lines.join("\n")}\n}\n`;

mkdirSync(join(root, "dist"), { recursive: true });
out("tokens.css", tokensCss);
out("fonts.css", banner + read("src/fonts.css"));
out("base.css", banner + read("src/base.css"));
out("components.css", banner + read("src/components.css"));
// dinsor.css: everything, one request. Font URLs resolve relative to dist/.
out("dinsor.css", banner + [read("src/fonts.css"), tokensCss.replace(banner, ""), read("src/base.css"), read("src/components.css")].join("\n"));

const pick = (g, f = (t) => t.value) => Object.fromEntries(Object.entries(tokens[g]).map(([k, t]) => [k, f(t)]));
const preset = {
  theme: {
    extend: {
      colors: pick("color"),
      fontFamily: Object.fromEntries(Object.entries(tokens.font).map(([k, t]) => [k, t.value.split(/,\s*(?=(?:[^"]*"[^"]*")*[^"]*$)/)])),
      borderRadius: pick("radius"),
      fontSize: Object.fromEntries(Object.entries(tokens.size).map(([k, t]) => [`ds-${k}`, t.value])),
      boxShadow: pick("shadow"),
    },
  },
};
out("tailwind.preset.cjs", `${banner}module.exports = ${JSON.stringify(preset, null, 2)};\n`);
const md = ["<!-- GENERATED by scripts/build.mjs from tokens/tokens.json. -->", "# Tokens", ""];
for (const [group, items] of Object.entries(tokens)) {
  if (group.startsWith("$")) continue;
  md.push(`## ${group}`, "", "| css variable | value | use |", "|---|---|---|");
  for (const [name, t] of Object.entries(items)) md.push(`| \`var(--${varName(group, name)})\` | \`${t.value.replace(/\|/g, "\\|")}\` | ${t.use} |`);
  md.push("");
}
out("tokens.md", md.join("\n"));
console.log("built dist/");
