// tokens/tokens.json + src/*.css -> dist/*. No dependencies.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(root, "tokens/tokens.json"), "utf8"));
const read = (p) => readFileSync(join(root, p), "utf8");
const out = (p, s) => writeFileSync(join(root, "dist", p), s);
const banner = "/* GENERATED by scripts/build.mjs. Edit tokens/tokens.json or src/*.css. */\n";

const varName = (group, name) =>
  ({ color: "", font: "", size: "text-", radius: "radius-", space: "space-", shadow: "shadow-", layout: "layout-" })[group] + name;

const lines = [];
for (const [group, items] of Object.entries(tokens)) {
  if (group.startsWith("$") || group === "themes") continue;
  for (const [name, t] of Object.entries(items)) lines.push(`  --${varName(group, name)}: ${t.value};`);
}
const tokensCss = `${banner}:root {\n${lines.join("\n")}\n}\n`;

// Themes: derive hover, tags and on-dark from each accent (hue-preserving, HSL).
const toRgb = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
const lum = (h) => toRgb(h).map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)).reduce((s, c, i) => s + c * [0.2126, 0.7152, 0.0722][i], 0);
const contrast = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05); };
const toHsl = (h) => {
  const [r, g, b] = toRgb(h), mx = Math.max(r, g, b), mn = Math.min(r, g, b), l = (mx + mn) / 2, d = mx - mn;
  if (!d) return [0, 0, l];
  const s = d / (1 - Math.abs(2 * l - 1));
  const hue = mx === r ? ((g - b) / d) % 6 : mx === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return [(hue * 60 + 360) % 360, s, l];
};
const fromHsl = (h, s, l) => {
  const c = (1 - Math.abs(2 * l - 1)) * s, x = c * (1 - Math.abs(((h / 60) % 2) - 1)), m = l - c / 2;
  const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return "#" + [r, g, b].map((v) => Math.round((v + m) * 255).toString(16).padStart(2, "0")).join("").toUpperCase();
};
const themeCss = [];
for (const [name, t] of Object.entries(tokens.themes)) {
  if (name.startsWith("$")) continue;
  const accent = t.value, [h, s, l] = toHsl(accent);
  const derived = {
    "--accent": accent,
    "--accent-hover": fromHsl(h, s, l * 0.75),
    "--tag": fromHsl(h, 0.22, 0.88),
    "--tag-quiet": fromHsl(h, 0.22, 0.92),
    "--accent-on-dark": fromHsl(h, Math.min(Math.max(s, 0.3), 0.5), 0.72),
  };
  const gates = [
    [contrast(accent, tokens.color.bg.value), 7, "accent on bg"],
    [contrast(tokens.color["accent-ink"].value, accent), 7, "accent-ink on accent"],
    [contrast(derived["--accent-on-dark"], tokens.color.dark.value), 7, "accent-on-dark on dark"],
    [contrast(tokens.color.ink.value, derived["--tag"]), 7, "ink on tag"],
  ];
  for (const [ratio, min, what] of gates) if (ratio < min) throw new Error(`theme ${name}: ${what} contrast ${ratio.toFixed(2)} < ${min}`);
  if (name !== "emerald") themeCss.push(`[data-theme="${name}"] {\n${Object.entries(derived).map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}\n`);
}
const themesCss = `${banner}${themeCss.join("\n")}`;

mkdirSync(join(root, "dist"), { recursive: true });
out("themes.css", themesCss);
out("tokens.css", tokensCss);
out("fonts.css", banner + read("src/fonts.css"));
out("base.css", banner + read("src/base.css"));
out("components.css", banner + read("src/components.css"));
// dinsor.css: everything, one request. Font URLs resolve relative to dist/.
out("dinsor.css", banner + [read("src/fonts.css"), tokensCss.replace(banner, ""), read("src/base.css"), read("src/components.css"), themesCss.replace(banner, "")].join("\n"));

const pick = (g, f = (t) => t.value) => Object.fromEntries(Object.entries(tokens[g]).map(([k, t]) => [k, f(t)]));
const preset = {
  theme: {
    extend: {
      colors: pick("color"),
      fontFamily: Object.fromEntries(Object.entries(tokens.font).map(([k, t]) => [k, t.value.split(/,\s*(?=(?:[^"]*"[^"]*")*[^"]*$)/)])),
      borderRadius: pick("radius"),
      fontSize: Object.fromEntries(Object.entries(tokens.size).map(([k, t]) => [`ds-${k}`, t.value])),
      boxShadow: pick("shadow"),
    },
  },
};
out("tailwind.preset.cjs", `${banner}module.exports = ${JSON.stringify(preset, null, 2)};\n`);
const md = ["<!-- GENERATED by scripts/build.mjs from tokens/tokens.json. -->", "# Tokens", ""];
for (const [group, items] of Object.entries(tokens)) {
  if (group.startsWith("$") || group === "themes") continue;
  md.push(`## ${group}`, "", "| css variable | value | use |", "|---|---|---|");
  for (const [name, t] of Object.entries(items)) md.push(`| \`var(--${varName(group, name)})\` | \`${t.value.replace(/\|/g, "\\|")}\` | ${t.use} |`);
  md.push("");
}
md.push("## themes", "", "Set `<html data-theme=\"name\">`. One theme per page. Hover, tags and on-dark derive from the accent.", "", "| theme | accent | feel |", "|---|---|---|");
for (const [name, t] of Object.entries(tokens.themes)) if (!name.startsWith("$")) md.push(`| \`${name}\` | \`${t.value}\` | ${t.use} |`);
md.push("");
out("tokens.md", md.join("\n"));
console.log("built dist/");
